services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-library-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json
    depends_on:
      - db
    networks:
      - home-library-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ${POSTGRES_HOST}    
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-todoapp} -d ${POSTGRES_DB:-todoapp}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - home-library-network

networks:
  home-library-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs: